language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libgsl0-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then brew update                     ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then brew install gsl                ; fi
script:
  - cmake .
  - cmake --build .
  - ctest --output-on-failure
