name: test

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        cxxflags: ["", "-Ofast -ffast-math"]

    steps:
    - name: ls
      run: echo $(find ../../ -name CMakeLists.txt) >&2
    - name: cmake
      run: cmake .
      env:
        CXXFLAGS: ${{ matrix.cxxflags }}
    - name: cmake build
      run: cmake --build .
    - name: ctest
      run: ctest
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
